enum QueryEngines {
  TFIDF = "TFIDF",
  BM25 = "BM25",
  SEMANTIC_KEYWORDS = "SEMANTIC_KEYWORDS",
  SEMANTIC_PASSAGE_EMBEDDINGS = "SEMANTIC_PASSAGE_EMBEDDINGS",
}

export enum CBIREngines {
  CLASSICAL = "CLASSICAL",
  DEEP = "DEEP",
  NONE = "NONE"
}

export default QueryEngines;
